/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'drugName' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const QuestionnaireResponse = IDL.Record({
  'patientName' : IDL.Text,
  'sideEffects' : IDL.Text,
  'missedDose' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addPatient' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addResponse' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getResponses' : IDL.Func([], [IDL.Vec(QuestionnaireResponse)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'drugName' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const QuestionnaireResponse = IDL.Record({
    'patientName' : IDL.Text,
    'sideEffects' : IDL.Text,
    'missedDose' : IDL.Bool,
  });
  
  return IDL.Service({
    'addPatient' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addResponse' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getResponses' : IDL.Func([], [IDL.Vec(QuestionnaireResponse)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };